### ISSUE TITLE
🚀 Add APIs to allow keeping device awake without using any Third Party Package

### ISSUE THREAD

**Issue by ygit** [100mslive/100ms-react-native#1087]

**Comment by rishavmehra** [comment]
Hey @ygit Can you Please Give me more context on it, I like to contribute on this Issue

**Comment by ygit** [comment]
hey @rishavmehra 
Thanks for chipping in. 🙌

I am sharing some more context for this ticket below -

- When a  Peer joins a Room, the phone's screen should not turn off as long as the Peer is in Room.
- The Peer can manually turn off the screen
- Automatic locking of the screen should not happen
