### ISSUE TITLE
🐛 TypeError: Cannot read property 'build' of null 

### ISSUE THREAD

**Issue by vyktoremario** [100mslive/100ms-react-native#1119]
### Description

When I run `await HMSSDK.buid()` I get an error `[TypeError: Cannot read property 'build' of null]`. The application uses Expo.

I followed the steps found on the documentation and I still get the same error. https://www.100ms.live/docs/react-native/v2/how-to-guides/install-the-sdk/integration
I also cloned one of the sample apps and I got the same error

### 100ms React Native Version

1.7.0

### Steps to reproduce

1. Start a react-native app with expo and install the 100ms dependency
2. Add the basic implementation for creating a video conference call or create a function that calls `await HMSSDK.buid()` and call the function inside the useEffect in the App.js
3. Check the log to see the above error printed out.

### Expected results

On calling `await HMSSDK.buid()`, I expect an instance of hms is returned so that I can have access to all the method in the class.

### Code example, screenshot, or link to a repository

<details>
<summary>Code sample</summary>

```jsx
 const ROOM_CODE = MODERATOR_ROOM_CODE;
  const AUTH_TOKEN = MODERATOR_AUTH_TOKEN;

  const hmsInstanceRef = useRef<HMSSDK | null>(null);
  
  const RoomScreen = ({ handleRoomEnd }) => {
    const [peerTrackNodes, setPeerTrackNodes] = useState([]);
    const [loading, setLoading] = useState(true);
  
    // Joining a room
    const onJoinSuccess = (data) => {
      const { localPeer } = data.room;
      setPeerTrackNodes([{ peer: localPeer, track: localPeer.videoTrack }]);
  
      setLoading(false);
    };
  
    //Listening for peers actions in a room
    const onPeerListener = ({ peer, type }) => {
      if (type === HMSPeerUpdate.PEER_LEFT) {
        setPeerTrackNodes((prevNodes) =>
          prevNodes.filter((node) => node.peer.peerID !== peer.peerID)
        );
      } else if (type !== HMSPeerUpdate.PEER_JOINED) {
        setPeerTrackNodes((prevNodes) =>
          prevNodes.map((node) =>
            node.peer.peerID === peer.peerID ? { ...node, peer } : node
          )
        );
      }
    };
  
    // Listen for audo, video track controls in a room by a peer
    const onTrackListener = ({ peer, track, type }) => {
      if (
        type === HMSTrackUpdate.TRACK_ADDED &&
        track.type === HMSTrackType.VIDEO
      ) {
        setPeerTrackNodes((prevNodes) => [...prevNodes, { peer, track }]);
      } else if (
        type === HMSTrackUpdate.TRACK_MUTED ||
        type === HMSTrackUpdate.TRACK_UNMUTED
      ) {
        setPeerTrackNodes((prevNodes) =>
          prevNodes.map((node) => {
            if (
              node.peer.peerID === peer.peerID &&
              node.track &&
              node.track.trackId === track.trackId
            ) {
              return { ...node, track };
            }
            return node;
          })
        );
      }
    };
  
    // Listen for error
    const onErrorListener = (error) => {
      setLoading(false);
      console.log(error?.description);
    };

    const getTrackSettings = ({
        mutedAudio,
        mutedVideo,
      }) => {
        let audioSettings = new HMSAudioTrackSettings({
          initialState: mutedAudio
            ? HMSTrackSettingsInitState.MUTED
            : HMSTrackSettingsInitState.UNMUTED,
        });
      
        let videoSettings = new HMSVideoTrackSettings({
          initialState: mutedVideo
            ? HMSTrackSettingsInitState.MUTED
            : HMSTrackSettingsInitState.UNMUTED,
          cameraFacing: HMSCameraFacing.FRONT,
          forceSoftwareDecoder: true,
        });
      
        return new HMSTrackSettings({
          video: videoSettings,
          audio: audioSettings,
        });
      };
  
    
    useEffect(() => {
      const joinRoom = async () => {
        try {
          setLoading(true);

          const trackSettings = getTrackSettings({
            mutedAudio: true,
            mutedVideo: true,
          });

          const hmsInstance = await HMSSDK.build({trackSettings});
          if (hmsInstance) {
            console.log("hmsInstance built");
          }
          hmsInstanceRef.current = hmsInstance;

          const token =
            AUTH_TOKEN || (await hmsInstance.getAuthTokenByRoomCode(ROOM_CODE));
  
          const config = new HMSConfig({ authToken: token, username: USERNAME });
          await hmsInstance.join(config);
  
          
          hmsInstance.addEventListener(
            HMSUpdateListenerActions.ON_JOIN,
            onJoinSuccess
          );
          hmsInstance.addEventListener(
            HMSUpdateListenerActions.ON_PEER_UPDATE,
            onPeerListener
          );
          hmsInstance.addEventListener(
            HMSUpdateListenerActions.ON_TRACK_UPDATE,
            onTrackListener
          );
          hmsInstance.addEventListener(
            HMSUpdateListenerActions.ON_ERROR,
            onErrorListener
          );
        } catch (error) {
          console.error(error);
          Alert.alert("Error", "Check your console to see error logs!");
        }
      };
  
      joinRoom();
  
      return () => {
        handleRoomEnd();
      };
    }, [handleRoomEnd]);
  
    const renderItem = ({ item }) => {
      const { peer, track } = item;
  
      return (
        <View
          style={{
            height: 300,
            margin: 8,
            borderRadius: 20,
            overflow: "hidden",
            backgroundColor: "#A0C3D2",
          }}
        >
          {track && track.type === HMSTrackType.VIDEO ? (
            <HMSSDK.HmsView
              trackId={track.trackId}
              mirror={peer.isLocal}
              style={{ width: "100%", height: "100%" }}
            />
          ) : (
            <View
              style={{ flex: 1, alignItems: "center", justifyContent: "center" }}
            >
              <View
                style={{
                  width: 100,
                  height: 100,
                  borderRadius: 50,
                  alignItems: "center",
                  justifyContent: "center",
                  backgroundColor: "#FD8A8A",
                }}
              >
                <Text
                  style={{
                    textAlign: "center",
                    fontSize: 28,
                    fontWeight: "bold",
                    textTransform: "uppercase",
                  }}
                >
                  {peer.name
                    .split(" ")
                    .map((item) => item[0])
                    .join("")}
                </Text>
              </View>
            </View>
          )}
        </View>
      );
    };
  
    return (
      <View style={{ flex: 1 }}>
        {loading ? (
          <View
            style={{ flex: 1, alignItems: "center", justifyContent: "center" }}
          >
            <ActivityIndicator size="large" color="#2471ED" />
          </View>
        ) : peerTrackNodes.length > 0 ? (
          <FlatList
            data={peerTrackNodes}
            renderItem={renderItem}
            keyExtractor={(item) => item.peer.peerID}
            contentContainerStyle={{ paddingBottom: 120 }}
          />
        ) : (
          <View
            style={{ flex: 1, alignItems: "center", justifyContent: "center" }}
          >
            <Text style={{ fontSize: 28, marginBottom: 32 }}>Welcome!</Text>
            <Text style={{ fontSize: 16 }}>You're the first one here.</Text>
            <Text style={{ fontSize: 16 }}>
              Sit back and relax till the others join.
            </Text>
          </View>
        )}
        <TouchableOpacity
          onPress={handleRoomEnd}
          style={{
            position: "absolute",
            bottom: 40,
            alignSelf: "center",
            backgroundColor: "#CC525F",
            width: 60,
            height: 60,
            borderRadius: 30,
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <Text
            style={{ textAlign: "center", color: "#ffffff", fontWeight: "bold" }}
          >
            Leave Room
          </Text>
        </TouchableOpacity>
      </View>
    );
  };
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

**Comment by stanwolverine** [comment]
@vyktoremario are you using expo go app?

**Comment by vyktoremario** [comment]
> @vyktoremario are you using expo go app?

@stanwolverine yes I am using Expo go app

**Comment by ygit** [comment]
@vyktoremario Have you done the Expo Dev Client setup?
Check the steps mentioned here: https://www.100ms.live/docs/react-native/v2/how-to-guides/install-the-sdk/integration#expo-setup
This is a sample app using Expo + 100ms React Native package: https://github.com/ygit/expo-react-native-hms

**Comment by vyktoremario** [comment]
> @vyktoremario Have you done the Expo Dev Client setup? Check the steps mentioned here: https://www.100ms.live/docs/react-native/v2/how-to-guides/install-the-sdk/integration#expo-setup This is a sample app using Expo + 100ms React Native package: https://github.com/ygit/expo-react-native-hms

I have followed the steps in the docs and it still doesn't work for me.(Mind you, expo-cli is deprecated  )
I will clone the repo you linked and see if it works for me. I Will respond back.

**Comment by ygit** [comment]
alright @vyktoremario 
Let us know.
We can also get on a call to debug this or any other help you need in integrating the 100ms package. 
Block a convenient time here: https://calendly.com/yogesh-singh-100ms/30min

**Comment by vyktoremario** [comment]
> > @vyktoremario Have you done the Expo Dev Client setup? Check the steps mentioned here: https://www.100ms.live/docs/react-native/v2/how-to-guides/install-the-sdk/integration#expo-setup This is a sample app using Expo + 100ms React Native package: https://github.com/ygit/expo-react-native-hms
> 
> @ygit I have followed the steps in the docs and it still doesn't work for me(Mind you, expo-cli is deprecated ) I will clone the repo you linked and see if it works for me. I Will respond back.

I just cloned the repo you linked and it still doesn't work for me. First, `expo-cli` is deprecated and they suggested to use `npx expo start` and that only works for version 47 and above. Secondly, when I run `expo start --dev-client`, the Expo Go app doesn't load/build the app at all(on an Android device) even when I scan the QR code. 
The repo uses expo version 44.0.0 while the application I am using is currently using 47.0.13.

Does this only work if I use Xcode or an Android emulator? Or do you expect this to work even with Expo Go app on an Android device?

**Comment by vyktoremario** [comment]
I just booked a time for tomorrow.
Looking forward to speaking to you guys about this issue

**Comment by ygit** [comment]
Sure. Likewise

**Comment by vyktoremario** [comment]
So, I was able to get past this issue. My colleagues were insisting on using Expo so I had to use Expo development build due to native code being required (as @ygit mentioned on the call). These are the steps I took:

1. Install eas cli 

```shell
npm install -g eas-cli
```
2. Install Expo dev client

```shell
npx expo install expo-dev-client
```
3. Log into my Expo account

```shell
eas login
```
4. Create a development build for android emulator or device. Link to docs https://docs.expo.dev/develop/development-builds/create-a-build/?redirected

```shell
eas build --profile development --platform android
```
5. Download the apk build and install it into your emulator (or device)
6. Start the local server using `npx expo start --dev-client`
7. Copy the local URL and past it on the installed app (required for the app to run)

This works fine and the `HMMSDK` class is being built and returns an instance. 

But I get the below error once in a while and I don't know if you guys have an idea why it is showing up.
Thanks

```
There's this error I get: 
Unable to resolve host "prod-init.100ms.live": No address associated with hostname. [SignalDisconnect] Could not recover in 60000 milli seconds.
```

**Comment by ygit** [comment]
hey @vyktoremario 
are you still facing this issue? is it happening everytime?

**Comment by vyktoremario** [comment]
> hey @vyktoremario are you still facing this issue? is it happening everytime?

@ygit I can confirm that I haven't had this error ever since that day. It looks to work as expected.

Thanks!

**Comment by ygit** [comment]
Nice 🙌
Let us know if you need help with anything else.
Closing this issue thread.

**Comment by vyktoremario** [comment]
While I am still here, I have a question.

Suppose I create a room on the 100ms dashboard and joined in as a moderator. Then copied one of the room codes and used it to join on my locally running development app, should I be able to see the user that joined on the dashboard or anyone that joins on the dashboard?  
Cos right now I don't. It shows I am the only one in the room on my end but also informs the dashboard user that I joined the room.
