### ISSUE TITLE
🐛 EXC_BAD_ACCESS: Exception 1, Code 8, Subcode 8 > Attempted to dereference garbage pointer 0x8.

### ISSUE THREAD

**Issue by DeepaliRai30** [100mslive/100ms-react-native#1122]
### Description

App is crashing on ios 
Getting this :  EXC_BAD_ACCESS: Exception 1, Code 8, Subcode 8 >
Attempted to dereference garbage pointer 0x8. 
but its working fine in simulator

### 100ms React Native Version

0.9.93

### React Native Version

0.70.1

### Steps to reproduce

getting this on real device while its working fine in simulator

### Expected results

user should able to join call

### Code example, screenshot, or link to a repository

<details>
<summary>Code sample</summary>

```dart
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

**Comment by stanwolverine** [comment]
Hi @DeepaliRai30 use the latest version `1.7.0` and check if the error is still happening

**Comment by ygit** [comment]
hey @DeepaliRai30 
Were you able resolve the issue on the latest version?
