### ISSUE TITLE
❓ When this error is reported and how to resolve this?

### ISSUE THREAD

**Issue by bhishakBitcanny** [100mslive/100ms-react-native#1266]
# ❓ Question or Support Request

## Describe your question or ask for support

`{"action": "INIT", "canRetry": undefined, "code": 401, "description": "Received ", "isTerminal": true, "message": "Bad Request", "name": "HTTPError"}`
Receiving this sometimes sporadically. Kindly let me know when this error is reported and how to resolve this?

"@100mslive/react-native-hms": "^1.9.2"
"react-native": "^0.67.5",
-

**Comment by ygit** [comment]
@bhishakBitcanny This is most likely an issue with Auth Token generation. 
Can you share a sample Auth Token used?

**Comment by bhishakBitcanny** [comment]
By auth token you mean the room_token used to initiate this call? @ygit

**Comment by bhishakBitcanny** [comment]
Example token - `eyJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3Nfa2V5IjoiNjRlZjBlYTRjYTU4NDhmMGUzZDQ2NjNhIiwicm9vbV9pZCI6IjY0ZWYzNTRkN2ZiODk1YmVkNmY3YTMwNSIsInVzZXJfaWQiOiI2NGVmMGVhNGNhNTg0OGYwZTNkNDY2MzgiLCJyb2xlIjoiaG9zdCIsInR5cGUiOiJhcHAiLCJqdGkiOiI0Zjc1ZDEzOC01ZjVlLTRiMjctYjUxZS1jNWY5MTliOWI4NjEiLCJleHAiOjE3MDAxNTE0NjB9.bskV-tCS3pOv58BwXzmhrOlaGUBTO5s892EJlWQa4dc`

**Comment by ygit** [comment]
@bhishakBitcanny can you try this Token: 
```
eyJhbGciOiJIUzI1NiJ9.eyJhY2Nlc3Nfa2V5IjoiNjRlZjBlYTRjYTU4NDhmMGUzZDQ2NjNhIiwicm9vbV9pZCI6IjY0ZWYzNTRkN2ZiODk1YmVkNmY3YTMwNSIsInVzZXJfaWQiOiI2NGVmMGVhNGNhNTg0OGYwZTNkNDY2MzgiLCJyb2xlIjoiaG9zdCIsInR5cGUiOiJhcHAiLCJqdGkiOiI0Zjc1ZDEzOC01ZjVlLTRiMjctYjUxZS1jNWY5MTliOWI4NjEiLCJ2ZXJzaW9uIjoyLCJleHAiOjE3MDA5NTE0NjB9.ls-pAW9fIRbEz_dmH-XhiSRjJ9jh15N201Lds8fZUNA
```

**Comment by bhishakBitcanny** [comment]
Thank you @ygit we resolved it on our end so closing this.
