### ISSUE TITLE
Query Regarding Room Usage in Audio/Video Calling Application 

### ISSUE THREAD

**Issue by kherajanid** [100mslive/100ms-react-native#1380]
Specifically, we are debating between two strategies for room usage:

1. Creating a new room every time a call is initiated.
2. Using a static room code that remains consistent for each user.

We would greatly appreciate your insights and recommendations on which approach would be best suited for our application. Your expertise in this area would be invaluable to us as we aim to provide the best user experience possible.

**Comment by ygit** [comment]
hey @kherajanid 
I hope you can resolve the query now.
