### ISSUE TITLE
❓  Task :100mslive_react-native-hms:minifyReleaseWithR8 FAILED

### ISSUE THREAD

**Issue by syedmohsin7975** [100mslive/100ms-react-native#1389]
![image](https://github.com/100mslive/100ms-react-native/assets/46786289/8653c0a4-cb64-4a72-bc40-5f735be22239)

I am getting this error and my build fails. Tried adding rules in proguard-rules.pro file but this issue still persist.

Need support on what could have gone wrong.

![image](https://github.com/100mslive/100ms-react-native/assets/46786289/c806ee58-ee64-49dc-91fa-2e8d7c01a72b)

![image](https://github.com/100mslive/100ms-react-native/assets/46786289/b6408047-2a7f-40b9-aa58-03fb05d7bc73)

I referred to docs, checked closed issue and also referred your sample app.

**Comment by syedmohsin7975** [comment]
I have already included relevant logs or detailed description. I am unable to build app getting error as mentioned above. Please help me here, tried enabling the R8 from build.gradle but got deprecated message. Add rules to from mapping file.

**Comment by ygit** [comment]
hey @syedmohsin7975 
What's the Gradle version used in your app?
Can you share your `gradle-wrapper.properties` file?

**Comment by ygit** [comment]
@syedmohsin7975 were you able to resolve this issue?

**Comment by ygit** [comment]
hey @syedmohsin7975 were you able to check this issue?

**Comment by syedmohsin7975** [comment]
Hi @ygit 

It seems that there's an issue with ProGuard minification. When disabled, everything works fine. However, enabling ProGuard causes R8 minification to fail. I'll need to check with the ProGuard repository to resolve this.

**Comment by minhaz19** [comment]
@syedmohsin7975 after doing minifyEnabled false still it's showing this error. How did you fix this?

Execution failed for task ':100mslive_react-native-hms:minifyReleaseWithR8'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
   > Compilation failed to complete

**Comment by namannangia** [comment]
Why is this issue closed, what was the official solution to this problem?

**Comment by Huzaifa-code** [comment]
I am also facing the same issue, I have tried everything but nothing seems to work

**Comment by syedmohsin7975** [comment]
> @syedmohsin7975 after doing minifyEnabled false still it's showing this error. How did you fix this?
> 
> > Execution failed for task ':100mslive_react-native-hms:minifyReleaseWithR8'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
> > Compilation failed to complete



> @syedmohsin7975 after doing minifyEnabled false still it's showing this error. How did you fix this?
> 
> > Execution failed for task ':100mslive_react-native-hms:minifyReleaseWithR8'.
> > A failure occurred while executing com.android.build.gradle.internal.tasks.R8Task$R8Runnable
> > Compilation failed to complete

There is one more place where you have to disable this, it is in the node modules of this library. Inside you will find build.gradle there also you have to disable the minifyenabled.

Ref links and lines below

https://github.com/100mslive/100ms-react-native/blob/main/packages/react-native-hms/android/build.gradle 
Line: 62

**Comment by minhaz19** [comment]
@syedmohsin7975 it's working. But it's making the app significantly large. I think there has to be a better solution from the maintainer.

**Comment by ygit** [comment]
Yes @minhaz19 
We'll come up with a proper fix soon
