### ISSUE TITLE
🚀 iPhone Home indicator issue with full screen video

### ISSUE THREAD

**Issue by satvicmovement** [100mslive/100ms-react-native#1438]
# 🚀 Feature Request

## Is your feature request related to a problem? Please describe
Home indicator can obscure subtitles on iphone devices with home indicator
![WhatsApp Image 2024-09-05 at 15 31 51](https://github.com/user-attachments/assets/18c6d000-52c8-47e2-aa02-c1cf79c1a354)

## **Describe the solution you'd like**
use of prefersHomeIndicatorAutoHidden or preferredScreenEdgesDeferringSystemGestures whichever solves the purpose

## **Describe alternatives you've considered**
https://www.youtube.com/watch?v=GdzDz1z-Gi8
https://www.youtube.com/watch?app=desktop&v=26GFXmC99p8

the solutions provided in the above links can be cumbersome for users

can't use autoHideHomeIndicator from @react-navigation/native-stack 

### Any Media to attach?
![WhatsApp Image 2024-09-05 at 15 31 51](https://github.com/user-attachments/assets/0daefbfc-4aa3-4ad9-86c4-5883958abc42)

**Comment by ygit** [comment]
@satvicmovement On which iPhone is this behaviour observed?

**Comment by ygit** [comment]
hey @satvicmovement I think these Captions are embedded within the video itself and are not the Captions generated by 100ms. Can you confirm this?
