### ISSUE TITLE
🐛 react-native-modal library version

### ISSUE THREAD

**Issue by kfssoftware** [100mslive/100ms-react-native#1455]
### Description

When react-native-modal library is in version 12.1.0, it gives the error "_reactNative.DeviceEventEmitter.removeListener is not a function". This problem disappears when the version of this library is 13.0.1. Can you update the version of the library and send the codes?

### 100ms React Native Version

0.64.4

### React Native Version

0.72.10

### Steps to reproduce

read

### Expected results

read

### Code example, screenshot, or link to a repository

<details>
<summary>Code sample</summary>

```js
```

### Logs

<details>
<summary>Logs</summary>

```console

<!-- Paste your logs here -->

```

</details>

**Comment by ygit** [comment]
@kfssoftware We have released `@100mslive/react-native-room-kit` version `1.2.3` which should fix this issue

**Comment by ygit** [comment]
hey @kfssoftware Were you able to check it on the latest `@100mslive/react-native-room-kit` version?

**Comment by ygit** [comment]
hey @kfssoftware Fix for this was released in version `1.2.3`
Closing this now
